name = "doudizhu"
main = "src/index.ts"
assets = { directory = "./dist" }
compatibility_date = "2026-05-01"

[[durable_objects.bindings]]
name = "LOBBY_DO"
class_name = "LobbyDO"

[[durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDO"

[[d1_databases]]
binding = "DB"
database_name = "doudizhu-db"
database_id = "local-dev"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LobbyDO", "RoomDO"]

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.prod]
vars = { ENVIRONMENT = "prod" }
[[env.prod.durable_objects.bindings]]
name = "LOBBY_DO"
class_name = "LobbyDO"

[[env.prod.durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDO"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "doudizhu-db"
database_id = "22154487-d775-4be7-8362-12e46137e2c8"